import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta
          name="description"
          content="Generated by create next app"
          typeof="asuidh asuiodh asiudh asiudh asdiuh asd"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Homepage
    </div>
  )
}

export default Home
